
import { Job } from './types';

// Fix: Updated MOCK_JOBS to conform to the Job interface.
export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    customer: 'Farmstead 101',
    driveHours: 2,
    buildType: 'New',
    manufacturer: 'GenericCorp',
    diameter: 48,
    rings: 8,
    bushels: 45,
    manHours: 320,
    crewSize: 4,
    sidedraw: false,
    stirator: false,
    topDry: false,
    daySweep: false,
    hopperBin: false,
  },
  {
    id: '2',
    customer: 'Greenfield Expansion',
    driveHours: 3,
    buildType: 'Extension',
    manufacturer: 'GenericCorp',
    diameter: 60,
    rings: 10,
    bushels: 90,
    manHours: 550,
    crewSize: 5,
    sidedraw: false,
    stirator: true,
    topDry: false,
    daySweep: false,
    hopperBin: false,
  },
  {
    id: '3',
    customer: 'North Ridge Silo',
    driveHours: 1,
    buildType: 'New',
    manufacturer: 'GenericCorp',
    diameter: 48,
    rings: 10,
    bushels: 55,
    manHours: 410,
    crewSize: 4,
    sidedraw: false,
    stirator: false,
    topDry: false,
    daySweep: false,
    hopperBin: false,
  },
    {
    id: '4',
    customer: 'South Valley Co-op',
    driveHours: 4,
    buildType: 'New',
    manufacturer: 'GenericCorp',
    diameter: 72,
    rings: 12,
    bushels: 150,
    manHours: 820,
    crewSize: 6,
    sidedraw: true,
    stirator: false,
    topDry: false,
    daySweep: true,
    hopperBin: false,
  },
  {
    id: '5',
    customer: 'Riverbend Farms',
    driveHours: 0.5,
    buildType: 'New',
    manufacturer: 'GenericCorp',
    diameter: 36,
    rings: 6,
    bushels: 20,
    manHours: 180,
    crewSize: 3,
    sidedraw: false,
    stirator: false,
    topDry: false,
    daySweep: false,
    hopperBin: true,
  },
];
